version: '3.8'

services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.41.0-jammy
    container_name: odise_playwright
    working_dir: /app
    volumes:
      - .:/app
    # Parameters to avoid memory issues and enable IPC
    ipc: host
    environment:
      - CI=true
    command: /bin/bash -c "npm install && npx playwright test"
